spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://os.com:9500  #认证中心端点，作为资源端的配置
          jwk-set-uri: http://os.com:9500/oauth2/jwks
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?useSSL= false&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root
    druid:
      stat-view-servlet:
        enabled: true
        loginUsername: admin
        loginPassword: 123456
      initial-size: 5
      min-idle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,slf4j
      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
  redis:
    database: 1
    host: localhost
    port: 6379
    password: 12345
    ssl: false
    timeout: 2000


mybatis-plus:
  mapper-locations: classpath*:/com/system/**/dao/mapping/*Mapper.xml
  typeAliasesPackage: com.system.modular.*.*.model
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #逻辑删除配置
    logic-delete-value: 1
    logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# token有效期时间
oauth2:
  access:
    token:
      time: 10
      unit: M
  refresh:
    token:
      time: 2
      unit: day

# 白名单
security:
  oauth2:
    whiteList:
      - /actuator/**
      - /error
      - /v3/api-docs
      - /feign/userDetails/loadUserByUsername
      - /user/captcha/check
      - /user/captcha
