server:
  port: 8080
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: @artifactId@
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
  config:
    import:
      - optional:nacos:${spring.application.name}-@profiles.active@.yaml
