server:
  port: 9500
spring:
  application:
    name: @artifactId@
  cloud:
    inetutils:
      ignored-interfaces: 'VMware Virtual Ethernet Adapter for VMnet1,VMware Virtual Ethernet Adapter for VMnet8'
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        namespace: dev
  config:
    import:
      - nacos:${spring.application.name}-@profiles.active@.yaml
